---
path: ../
memory: 1G
stack: cflinuxfs3
buildpack: python_buildpack
env:
  WEB_CONCURRENCY: 4
services:
  - fec-api-search56
  - fec-redis
  - fec-creds-dev
  - fec-s3-dev
applications:
  - name: celery-beat
    instances: 1
    memory: 256M
    no-route: true
    health-check-type: process
    command: celery beat --app webservices.tasks --loglevel INFO
