---
path: ../
memory: 1G
stack: cflinuxfs3
buildpack: python_buildpack
env:
  FEC_API_USE_PROXY: true
  FEC_API_RESTRICT_DOWNLOADS: true
  APP_NAME: fec | api | stage
  WEB_CONCURRENCY: 4
services:
  - fec-api-search56
  - fec-redis
  - fec-creds-stage
  - fec-s3-stage
routes:
  - route: fec-stage-api.app.cloud.gov
applications:
  - name: api
    instances: 1
