---
path: ../
memory: 1G
stack: cflinuxfs2
buildpack: python_buildpack
env:
  CACHE_ALL_REQUESTS: True
  FEC_API_WHITELIST_IPS: true
  NEW_RELIC_APP_NAME: fec | celery beat | prod
  NEW_RELIC_CONFIG_FILE: /home/vcap/app/newrelic.ini
  NEW_RELIC_ENV: production
  NEW_RELIC_LOG: stdout
  PRODUCTION: True
  WEB_CONCURRENCY: 4
services:
  - fec-api-search56
  - fec-redis
  - fec-creds-prod
  - fec-s3-prod
applications:
  - name: celery-beat
    instances: 1
    memory: 500M
    no-route: true
    health-check-type: process
    command: celery beat --app webservices.tasks --loglevel INFO
