---
path: ../
memory: 1G
stack: cflinuxfs3
buildpack: python_buildpack
env:
  FEC_API_WHITELIST_IPS: true
  PRODUCTION: True
  WEB_CONCURRENCY: 4
services:
  - fec-api-search56
  - fec-redis
  - fec-creds-prod
  - fec-s3-prod
routes:
  - route: fec-prod-api.app.cloud.gov
applications:
  - name: api
    instances: 8
