---
inherit: manifest_prod.yml
env:
  NEW_RELIC_APP_NAME: fec | celery worker | prod
applications:
  - name: celery-worker
    instances: 6
    memory: 1G
    disk_quota: 2G
    no-route: true
    health-check-type: process
    command: celery worker --app webservices.tasks --loglevel INFO --concurrency 3
