---
path: ../
memory: 1500M # 1.5G
stack: cflinuxfs3
buildpack: python_buildpack
env:
  APP_NAME: fec | api | dev
services:
  - fec-api-search56
  - fec-redis
  - fec-creds-dev
  - fec-s3-dev
routes:
  - route: fec-dev-api.app.cloud.gov
applications:
  - name: api
    instances: 1
    disk_quota: 1G
