---
path: ../
memory: 1G
stack: cflinuxfs3
buildpack: python_buildpack
env:
  WEB_CONCURRENCY: 4
services:
  - fec-api-search56
  - fec-redis
  - fec-creds-dev
  - fec-s3-dev
applications:
  - name: celery-worker
    instances: 2
    memory: 1G
    no-route: true
    health-check-type: process
    command: celery worker --app webservices.tasks --loglevel ${LOGLEVEL:=INFO} --concurrency 2
