---
path: ../
memory: 1G
stack: cflinuxfs2
buildpack: https://github.com/cloudfoundry/python-buildpack/releases/download/v1.6.1/python-buildpack-v1.6.1.zip
env:
  NEW_RELIC_CONFIG_FILE: /home/vcap/app/newrelic.ini
  NEW_RELIC_LOG: stdout
  WEB_CONCURRENCY: 4
services:
  - fec-api-search
  - fec-redis
